CC=g++

SOURCE=Utility.cpp Building.cpp Floor.cpp Room.cpp AccessPoint.cpp Menu.cpp Iannelson_finalproject.cpp

CFLAGS=-Wall -Werror -g -v $(SOURCE)
OUT=-o project_final

all:
	    $(CC) $(CFLAGS) $(LDFLAGS) $(OUT)
